name: ai-education
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - boto3
  - matplotlib
  - scikit-learn
  - numpy
  - tiktoken
  - pandas
  - html2text
  - beautifulsoup4
  - faiss-cpu
  - mcp
  - ipykernel
  - pip 