name: ai-education-data-pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=22.0.0
  - bs4>=4.12.0
  - numpy>=1.24.0
  - requests>=2.31.0
  - tqdm>=4.66.0
  - supabase
  - sentence-transformers>=2.2.2
  - python-dotenv>=1.0.0