name: ai-education-data-pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=22.0.0
  - bs4>=4.12.0
  - numpy>=1.24.0
  - requests>=2.31.0
  - tqdm>=4.66.0
  - pip:
    - openai==1.12.0
    - supabase==2.15.2
    - anthropic==0.52.1
    - tenacity==8.2.3